# Generated by Django 3.1.4 on 2020-12-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20201221_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cash',
            field=models.IntegerField(default=10000),
        ),
    ]
