# Generated by Django 3.1.4 on 2020-12-27 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_user_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
