# Generated by Django 3.1.4 on 2021-01-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20201230_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocks',
            name='sell_price',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
