# Generated by Django 3.1.4 on 2021-01-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20210106_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstocks',
            name='sell_price',
            field=models.DecimalField(decimal_places=1, max_digits=15),
        ),
    ]
