# Generated by Django 3.1 on 2020-09-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200925_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='product_img_url',
            field=models.CharField(default='https://hbr.org/resources/images/article_assets/2019/11/Nov19_14_sb10067951dd-001.jpg', max_length=300),
            preserve_default=False,
        ),
    ]
