# Generated by Django 3.1 on 2020-09-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_product_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='product_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='product_img_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='auction_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_qty',
            new_name='bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bid_timestamp',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_timestamp',
            new_name='timestamp',
        ),
    ]
