# Generated by Django 3.1 on 2020-10-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auction_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_bids', to='auctions.auction'),
        ),
    ]
