# Generated by Django 3.1 on 2020-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201005_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='has_bids',
            field=models.BooleanField(default=False),
        ),
    ]
