# Generated by Django 3.1 on 2020-10-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_has_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='has_bids',
        ),
    ]
