# Generated by Django 3.1 on 2020-10-10 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_auction_has_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
