# Generated by Django 3.1 on 2020-10-11 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auction_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default=None, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
