# Generated by Django 3.1 on 2020-10-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201012_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
