# Generated by Django 3.1 on 2020-10-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auction_is_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='is_open',
            new_name='is_active',
        ),
    ]
