# Generated by Django 3.1.3 on 2020-11-28 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='_user_follow_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
